<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
	<RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Bit.BlazorUI" Version="10.6.2" />
	  <PackageReference Include="Bit.BlazorUI.Assets" Version="10.6.2" />
	  <PackageReference Include="Bit.BlazorUI.Icons" Version="10.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LedgerLite.Contracts\LedgerLite.Contracts.csproj" />
  </ItemGroup>

</Project>
